{
    "name": 'Base Farmaku',
    "summary": "Base Farmaku",
    "version": "14.0.1.0.0",
    "author": "Arkana",
    "website": "https://arkana.co.id",
    "category": "Inventory",
    "depends": ['stock', 'sale'],
    "license": "LGPL-3",
    "data": [
        "security/ir.model.access.csv",
        "data/product_move_category.xml",
        "views/menuitem.xml",
        "views/product_view.xml",
        "views/category_farmaku_view.xml",
        "views/ingredient_view.xml",
        "views/principal_view.xml",
        "views/product_brand_view.xml",
        "views/product_variant_view.xml",
        "views/sale_view.xml",
        "views/tag_view.xml",
    ],
    'installable': True,
}
